# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: |
    mkdir -p deps
  displayName: 'setup'
- bash: |
    cd deps &&
    curl -L https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz -o libevent-2.1.8-stable.tar.gz &&
    tar xvf libevent-2.1.8-stable.tar.gz && 
    cd libevent-2.1.8-stable && 
    ./configure && 
    make -j8 && 
    sudo make -j8 install && 
    cd ..
  displayName: 'libevent'
- bash: |
    cd deps &&
    wget https://github.com/google/glog/archive/v0.3.5.tar.gz && 
    tar xvf v0.3.5.tar.gz && cd glog-0.3.5 && 
    ./configure && 
    make -j8 && 
    sudo make -j8 install && 
    cd ..
  displayName: 'glog'
- bash: |
    cd deps &&
    git clone https://github.com/gperftools/gperftools.git && 
    cd gperftools && git checkout gperftools-2.7 &&
    (./autogen.sh || ./autogen.sh) &&
    ./configure && 
    make -j8 && 
    sudo make -j8 install && 
    cd ..
  displayName: 'gperftools'
- bash: |
    cd deps &&
    git clone https://github.com/corehacker/ch-cpp-utils.git && 
    cd ch-cpp-utils && 
    ./autogen.sh && 
    ./configure && 
    make -j8 && 
    sudo make -j8 install && 
    cd ..
  displayName: 'ch-cpp-utils'
- script: |
    ./autogen.sh &&
    ./configure &&
    make -j8
  displayName: 'ch-storage-client'
